'@type': ORGANIZATION
name: accelerated_capability_environment
slug: accelerated_capability_environment
label: Accelerated Capability Environment
aliases:
- ACE
website: https://www.gov.uk/government/organisations/accelerated-capability-environment
source: https://www.gov.uk/api/organisations/accelerated-capability-environment
tags:
- govuk
- uk-government
- organization
- govuk-status:live
- govuk-format:sub_organisation
external_ids:
  govuk_content_id: 92bbe2da-8d5f-480b-8da1-50b18e317654
  govuk_analytics_identifier: OT1369
  govuk_slug: accelerated-capability-environment
govuk:
  title: Accelerated Capability Environment
  format: Sub organisation
  updated_at: '2023-05-24T14:14:28Z'
  abbreviation: ACE
  logo_formatted_name: Accelerated Capability Environment
  organisation_brand_colour_class_name: home-office
  organisation_logo_type_class_name: custom
  govuk_status: live
relationships:
  parent_organisations:
  - home_office
provenance:
  source_system: GOV.UK Organisations API
  api_url: https://www.gov.uk/api/organisations/accelerated-capability-environment
  retrieved_at: '2026-03-11T17:39:59Z'
